[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bayco"
version = "0.1.0"
description = "Bayesian co-expression network inference for transcriptomic data."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib"
]